title: "Our Beautiful Barnegat"
description: "Civic pride. Love of nature. Young leadership. The founding chapter of Our Beautiful America, started by Barnegat High School students."

url: "https://barnegat.ourbeautiful.org"
baseurl: ""

markdown: kramdown
permalink: pretty

collections:
  updates:
    output: true
    permalink: /updates/:path/

defaults:
  - scope:
      path: ""
      type: "updates"
    values:
      layout: "update"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
